export const resources = [
  {
    category: "Frontend",
    title: "HTML",
    url: "https://web.dev/html",
    description: "Learn the building blocks of the web.",
  },
  {
    category: "Frontend",
    title: "CSS",
    url: "https://web.dev/css",
    description: "Style your web pages beautifully.",
  },
  {
    category: "Frontend",
    title: "Tailwind CSS",
    url: "https://tailwindcss.com",
    description: "Utility-first CSS framework for fast UI design.",
  },
  {
    category: "Frontend",
    title: "JavaScript",
    url: "https://javascript.info",
    description: "Modern, deep JavaScript tutorials and guides.",
  },
  {
    category: "Frontend",
    title: "TypeScript",
    url: "https://www.typescriptlang.org/docs",
    description: "Typed JavaScript for scalable applications.",
  },
  {
    category: "Frontend",
    title: "React",
    url: "https://react.dev/learn",
    description: "Learn React from the official documentation.",
  },
  {
    category: "Frontend",
    title: "Next.js",
    url: "https://nextjs.org/learn",
    description: "Official Next.js tutorials and projects.",
  },
  {
    category: "Frontend",
    title: "Vue.js",
    url: "https://vuejs.org/guide/introduction.html",
    description: "The Progressive JavaScript Framework.",
  },
  {
    category: "Frontend",
    title: "Svelte",
    url: "https://svelte.dev/tutorial",
    description: "Learn the reactive, compile-time JS framework.",
  },
 
  {
    category: "Backend",
    title: "Node.js",
    url: "https://nodejs.dev/en/learn/",
    description: "Server-side JavaScript fundamentals.",
  },
  {
    category: "Backend",
    title: "Express.js",
    url: "https://expressjs.com/en/starter/installing.html",
    description: "Minimal and flexible Node.js framework.",
  },
  {
    category: "Backend",
    title: "Django",
    url: "https://docs.djangoproject.com/en/stable/",
    description: "High-level Python web framework for rapid development.",
  },
  {
    category: "Backend",
    title: "Flask",
    url: "https://flask.palletsprojects.com/en/latest/",
    description: "Lightweight WSGI web framework for Python.",
  },
  {
    category: "Backend",
    title: "FastAPI",
    url: "https://fastapi.tiangolo.com/",
    description: "Modern, fast (high-performance) Python web API framework.",
  },
  {
    category: "Backend",
    title: "Laravel",
    url: "https://laravel.com/docs",
    description: "Elegant PHP framework for web artisans.",
  },
  {
    category: "Backend",
    title: "Ruby on Rails",
    url: "https://guides.rubyonrails.org/",
    description: "Opinionated web framework for rapid development.",
  },
 
  {
    category: "Data & Algorithms",
    title: "Data Structures & Algorithms (NeetCode)",
    url: "https://neetcode.com",
    description: "Practice DSA and system design problems interactively.",
  },
  {
    category: "Data & Algorithms",
    title: "Algorithm Visualizer",
    url: "https://algorithm-visualizer.org",
    description: "Visualize algorithms and data structures in action.",
  },
  {
    category: "Data & Algorithms",
    title: "LeetCode",
    url: "https://leetcode.com",
    description: "Solve coding problems for interviews.",
  },
  {
    category: "Data & Algorithms",
    title: "HackerRank",
    url: "https://www.hackerrank.com/domains/tutorials/10-days-of-javascript",
    description: "Practice programming skills with challenges.",
  },
 
  {
    category: "Programming Languages",
    title: "Python",
    url: "https://realpython.com",
    description: "Comprehensive tutorials and projects in Python.",
  },
  {
    category: "Programming Languages",
    title: "C",
    url: "https://learn-c.org",
    description: "Interactive C language tutorials.",
  },
  {
    category: "Programming Languages",
    title: "C++",
    url: "https://fluentcpp.com",
    description: "Learn modern C++ and clean code techniques.",
  },
  {
    category: "Programming Languages",
    title: "Java",
    url: "https://www.baeldung.com/",
    description: "Learn Java and Spring framework in depth.",
  },
  {
    category: "Programming Languages",
    title: "Go",
    url: "https://learn-golang.org",
    description: "Interactive tutorials for the Go programming language.",
  },
  {
    category: "Programming Languages",
    title: "PHP",
    url: "https://www.learn-php.org",
    description: "Interactive PHP tutorials and projects.",
  },
  {
    category: "Programming Languages",
    title: "Swift",
    url: "https://codewithchris.com",
    description: "Learn Swift and iOS development from scratch.",
  },
  {
    category: "Programming Languages",
    title: "C#",
    url: "https://learncs.org",
    description: "Interactive C# tutorials for beginners.",
  },
 
  {
    category: "Databases & APIs",
    title: "SQL",
    url: "https://sqlbolt.com",
    description: "Interactive lessons to master SQL.",
  },
  {
    category: "Databases & APIs",
    title: "MongoDB",
    url: "https://www.mongodb.com/docs/",
    description: "Learn NoSQL and MongoDB CRUD operations.",
  },
  {
    category: "Databases & APIs",
    title: "REST APIs",
    url: "https://rapidapi.com/learn",
    description: "Learn how to build and consume APIs.",
  },
  {
    category: "Databases & APIs",
    title: "GraphQL",
    url: "https://graphql.org/learn/",
    description: "Learn the query language for APIs.",
  },
 
  {
    category: "DevOps & Cloud",
    title: "Git & GitHub",
    url: "https://git-scm.com",
    description: "Version control and collaboration essentials.",
  },
  {
    category: "DevOps & Cloud",
    title: "Docker",
    url: "https://docs.docker.com/get-started/",
    description: "Containerize applications easily.",
  },
  {
    category: "DevOps & Cloud",
    title: "Kubernetes",
    url: "https://kubernetes.io/docs/tutorials/",
    description: "Container orchestration tutorials and guides.",
  },
  {
    category: "DevOps & Cloud",
    title: "DevOps Cube",
    url: "https://devopscube.com",
    description: "Learn modern DevOps practices and tools.",
  },
  {
    category: "DevOps & Cloud",
    title: "AWS",
    url: "https://aws.amazon.com/training/",
    description: "Free AWS Cloud Practitioner training.",
  },
 
  {
    category: "AI & Machine Learning",
    title: "TensorFlow",
    url: "https://www.tensorflow.org/resources/learn-ml",
    description: "Build and deploy machine learning models.",
  },
  {
    category: "AI & Machine Learning",
    title: "PyTorch",
    url: "https://pytorch.org/tutorials/",
    description: "Learn deep learning using PyTorch.",
  },
  {
    category: "AI & Machine Learning",
    title: "Google AI",
    url: "https://ai.google/education/",
    description: "Educational AI resources from Google.",
  },
  {
    category: "AI & Machine Learning",
    title: "Hugging Face",
    url: "https://huggingface.co/learn",
    description: "Learn natural language processing with open-source models.",
  },
  {
    category: "AI & Machine Learning",
    title: "Machine Learning Crash Course",
    url: "https://developers.google.com/machine-learning/crash-course",
    description: "Fast-paced, practical intro to ML from Google.",
  },
 
  {
    category: "Web3 & Blockchain",
    title: "LearnWeb3",
    url: "https://learnweb3.io",
    description: "Beginner to advanced Web3 tutorials.",
  },
  {
    category: "Web3 & Blockchain",
    title: "CryptoZombies",
    url: "https://cryptozombies.io",
    description: "Learn Solidity by building a simple game.",
  },
  {
    category: "Web3 & Blockchain",
    title: "Alchemy University",
    url: "https://university.alchemy.com",
    description: "Learn blockchain and Web3 development interactively.",
  },
];